# Generated by Django 3.1.2 on 2020-10-27 10:44

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('tutorial_image', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='tutorial_image')),
                ('tutorial_content', models.TextField()),
                ('tutorial_author', models.CharField(max_length=60)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('prof_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='tutorialapp.profile')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
