# Generated by Django 3.1.2 on 2020-10-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialapp', '0002_tutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_author',
            field=models.CharField(max_length=30),
        ),
    ]
