# Generated by Django 3.1.2 on 2020-10-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialapp', '0004_tutorial_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
